# Generated by Django 3.2.5 on 2022-09-11 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
